# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  clone-and-copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout based.cooking
        uses: actions/checkout@v2
        with: 
          repository: LukeSmithxyz/based.cooking
          path: based.cooking
      - name: transfer files
        run: |
          mkdir -p main/src/based.cooking/pix && mkdir -p main/src/based.cooking/markdown
          cp -r based.cooking/data/pix main/src/based.cooking/pix
          cp -r based.cooking/src main/src/based.cooking/markdown
          ls main/src/based.cooking
      - name: push to repo
        run: |
          cd main
          git config --global user.name 'ScottEnock'
          git config --global user.email '27223098+ScottEnock@users.noreply.github.com'
          git commit -am "parity"
          git push
